//! 日文标签/属性翻译：兼容老式 Shimeji-ee 日文 XML 桌宠包。

/// 精确匹配的词元翻译：命中映射表返回英文词元，否则原样返回。
/// 适用于节点名、属性名与属性值。
pub fn translate_token(s: &str) -> &str {
    const MAP: &[(&str, &str)] = &[
        ("動作リスト", "ActionList"),
        ("動作", "Action"),
        ("動作参照", "ActionReference"),
        ("名前", "Name"),
        ("値", "Value"),
        ("種類", "Type"),
        ("クラス", "Class"),
        ("組み込み", "Embedded"),
        ("移動", "Move"),
        ("静止", "Stay"),
        ("固定", "Animate"),
        ("複合", "Sequence"),
        ("選択", "Select"),
        ("枠", "BorderType"),
        ("天井", "Ceiling"),
        ("壁", "Wall"),
        ("地面", "Floor"),
        ("目的地X", "TargetX"),
        ("目的地Y", "TargetY"),
        ("速度", "VelocityParam"),
        ("初速X", "InitialVX"),
        ("初速Y", "InitialVY"),
        ("重力", "Gravity"),
        ("空気抵抗X", "ResistanceX"),
        ("空気抵抗Y", "ResistanceY"),
        ("右向き", "LookRight"),
        ("IEの端X", "IeOffsetX"),
        ("IEの端Y", "IeOffsetY"),
        ("生まれる場所X", "BornX"),
        ("生まれる場所Y", "BornY"),
        ("生まれた時の行動", "BornBehavior"),
        ("行動", "Behavior"),
        ("繰り返し", "Loop"),
        ("アニメーション", "Animation"),
        ("条件", "Condition"),
        ("画像", "Image"),
        ("基準座標", "ImageAnchor"),
        ("移動速度", "Velocity"),
        ("長さ", "Duration"),
        ("行動リスト", "BehaviorList"),
        ("マウスの周りに集まる", "ChaseMouse"),
        ("頻度", "Frequency"),
        ("定数", "Constant"),
        ("次の行動リスト", "NextBehaviorList"),
        ("追加", "Add"),
        ("行動参照", "BehaviorReference"),
        ("落下する", "Fall"),
        ("ドラッグされる", "Dragged"),
        ("投げられる", "Thrown"),
        ("端X", "OffsetX"),
        ("端Y", "OffsetY"),
        ("マスコット", "Mascot"),
        ("ポーズ", "Pose"),
    ];
    MAP.iter()
        .find_map(|(from, to)| (s == *from).then_some(*to))
        .unwrap_or(s)
}
