name: "✨ 功能请求 / Feature Request"
description: "提出新功能或改进建议 / Suggest a new feature or improvement"
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你的建议！请描述你希望添加的功能。
        Thanks for your suggestion! Please describe the feature you'd like.

  - type: textarea
    id: problem
    attributes:
      label: "问题背景 / Problem"
      description: "这个功能解决什么问题？/ What problem does this feature solve?"
      placeholder: "当我 ... 的时候很不方便 / It's inconvenient when I ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "期望的解决方案 / Proposed Solution"
      description: "你希望如何实现？/ How would you like it to work?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "替代方案 / Alternatives Considered"
      description: "你考虑过其他方案吗？/ Have you considered any alternatives?"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "其他信息 / Additional Context"
      description: "截图、参考链接等 / Screenshots, reference links, etc."
    validations:
      required: false
